### ISSUE TITLE
Server crashes due to an exception being thrown

### ISSUE THREAD

**Issue by loftyD** [FlailoftheLord/ThrowableFireballs#3]
Hello!

I'm on Spigot 1.16.1

I've installed the plugin without any problems and had a session playing around with it.

Upon rejoining my server, the game crashes and throws the below exception:

```
23.11 00:07:51 [Server] Server thread/ERROR Encountered an unexpected exception
23.11 00:07:51 [Server] INFO net.minecraft.server.v1_16_R1.ReportedException: Ticking entity
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1119) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
23.11 00:07:51 [Server] INFO Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R1.entity.CraftLargeFireball cannot be cast to org.bukkit.entity.LivingEntity
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.IProjectile.setShooter(IProjectile.java:26) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityFireball.damageEntity(EntityFireball.java:162) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityLargeFireball.a(EntityLargeFireball.java:46) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.IProjectile.a(IProjectile.java:113) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityLargeFireball.a(EntityLargeFireball.java:21) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityFireball.tick(EntityFireball.java:61) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.World.a(World.java:753) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:394) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1106) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO ... 5 more
23.11 00:07:51 [Server] Server thread/ERROR Cause of unexpected exception was
23.11 00:07:51 [Server] INFO java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R1.entity.CraftLargeFireball cannot be cast to org.bukkit.entity.LivingEntity
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.IProjectile.setShooter(IProjectile.java:26) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityFireball.damageEntity(EntityFireball.java:162) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityLargeFireball.a(EntityLargeFireball.java:46) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.IProjectile.a(IProjectile.java:113) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityLargeFireball.a(EntityLargeFireball.java:21) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.EntityFireball.tick(EntityFireball.java:61) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.World.a(World.java:753) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.WorldServer.doTick(WorldServer.java:394) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1106) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
23.11 00:07:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
23.11 00:07:51 [Server] Server thread/ERROR This crash report has been saved to: /./crash-reports/crash-2020-11-23_00.07.51-server.txt
```

If necessary, I can attach my config.yml too.

Thanks

loftyD

**Comment by FlailoftheLord** [comment]
Whoops, sorry for the late reply, that's caused by the server unloading the world chunks while a fireball is mid-flight, then re loading them and not recognizing the fireball as a valid entity.
Simply kill any entities and your server will be okay.
