### ISSUE TITLE
Issue with ThrowableFireballs

### ISSUE THREAD

**Issue by marcelschoen** [FlailoftheLord/ThrowableFireballs#4]
Whenever I throw a fireball, I see a NullPointerException in the log:

`
2021-12-15 23:52:56 [ERROR] Could not pass event EntityExplodeEvent to ThrowableFireballs v1.9.0
java.lang.NullPointerException: Cannot invoke "me.flail.throwablefireballs.ThrowableFireballs.getConfig()" because "this.plugin" is null
	at me.flail.throwablefireballs.handlers.FireballExplosion.blockBoom(FireballExplosion.java:127) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-77]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.level.Explosion.a(Explosion.java:314) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.World.a(World.java:1010) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:1617) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.World.a(World.java:1003) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.entity.projectile.EntityLargeFireball.a(EntityLargeFireball.java:42) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.entity.projectile.IProjectile.preOnHit(IProjectile.java:172) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.entity.projectile.EntityFireball.k(EntityFireball.java:96) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:1128) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.World.a(World.java:970) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.server.level.WorldServer.lambda$tick$5(WorldServer.java:670) ~[paper-1.18.1.jar:git-Paper-77]
	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-77]
`

I am running this on a PaperMC 1.18.1-77 server
[config.yml.txt](https://github.com/FlailoftheLord/ThrowableFireballs/files/7723269/config.yml.txt)
.

**Comment by FlailoftheLord** [comment]
unable to replicate, will update github with fixes.
