### ISSUE TITLE
Is it up to date? yes i think so

### ISSUE THREAD

**Issue by Teals53** [FlailoftheLord/ThrowableFireballs#6]
[03:25:22 INFO]: [ThrowableFireballs] Enabling ThrowableFireballs v1.9.3
[03:25:22 ERROR]: Error occurred while enabling ThrowableFireballs v1.9.3 (Is it up to date?)
java.lang.IllegalArgumentException: Material cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:85) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:60) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:46) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at me.flail.throwablefireballs.handlers.FireballItem.fireball(FireballItem.java:49) ~[?:?]
        at me.flail.throwablefireballs.ThrowableFireballs.registerRecipes(ThrowableFireballs.java:214) ~[?:?]
        at me.flail.throwablefireballs.ThrowableFireballs.onEnable(ThrowableFireballs.java:99) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.jar:git-Paper-42]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-42]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[03:25:22 INFO]: [ThrowableFireballs] Disabling ThrowableFireballs v1.9.3
[03:25:22 INFO]: [ThrowableFireballs] Farewell!

**Comment by FlailoftheLord** [comment]
Check your recipe configuration, it's trying to create a null MaterialType. @Teals53

**Comment by Teals53** [comment]
the fun fact im using default config its same even i delete the config file

**Comment by Teals53** [comment]
@FlailoftheLord

**Comment by FlailoftheLord** [comment]
> the fun fact im using default config its same even i delete the config file

@Teals53 Try the pre-release here.
https://github.com/FlailoftheLord/ThrowableFireballs/releases/tag/1.9.4
let me know if you still encounter the issue.

**Comment by Teals53** [comment]
now its fixed with this hotfix thx

**Comment by FlailoftheLord** [comment]
https://github.com/FlailoftheLord/ThrowableFireballs/commit/3a7613a60cc9e2be8eb761af8430f67c6df73c11

https://github.com/FlailoftheLord/ThrowableFireballs/releases/tag/1.9.4

**Comment by Teals53** [comment]
[19:26:28 ERROR]: Could not pass event EntityExplodeEvent to ThrowableFireballs v1.9.4
java.lang.NullPointerException: Cannot read field "immuneBlocks" because "this.plugin" is null
        at me.flail.throwablefireballs.handlers.FireballExplosion.blockBoom(FireballExplosion.java:128) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-42]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.Explosion.finalizeExplosion(Explosion.java:332) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.world.level.Level.explode(Level.java:942) ~[?:?]
        at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1737) ~[?:?]
        at net.minecraft.world.level.Level.explode(Level.java:935) ~[?:?]
        at net.minecraft.world.entity.projectile.LargeFireball.onHit(LargeFireball.java:42) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractHurtingProjectile.tick(AbstractHurtingProjectile.java:96) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:898) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-42]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Teals53** [comment]
@FlailoftheLord another one happens while using fireball
